apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - works-pvc.yaml
  - identity.yaml
  - organization.yaml
  - works.yaml
  - governance.yaml
  - notify.yaml
  - gateway.yaml
  - web.yaml
  - hpa.yaml
