import { Alert, Button, Stack, Typography } from '@mui/material';
import { useState } from 'react';
import { PageHeader } from '../../components/PageHeader';
import { reportsApi } from '../../services/api/reports';

export function ReportsPage() {
  const [error, setError] = useState<string | null>(null);

  async function run(fn: () => Promise<void>) {
    setError(null);
    try {
      await fn();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed.');
    }
  }

  return (
    <>
      <PageHeader
        title="Reports"
        description="CSV export is generated by the owning service (Works or Governance) under the same district scope as the APIs."
      />
      <Stack spacing={2} maxWidth={560}>
        {error ? <Alert severity="error">{error}</Alert> : null}
        <Typography variant="body2" color="text.secondary">
          Large exports can later become jobs. These downloads stream through the gateway without storing files in PostgreSQL.
        </Typography>
        <Button variant="contained" sx={{ alignSelf: 'flex-start' }} onClick={() => void run(reportsApi.downloadProjects)}>
          Download projects CSV
        </Button>
        <Button variant="outlined" sx={{ alignSelf: 'flex-start' }} onClick={() => void run(reportsApi.downloadActions)}>
          Download actions CSV
        </Button>
      </Stack>
    </>
  );
}
